channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip:
    - clip==0.2.0
    - matplotlib==3.8.3
    - open-clip-torch==2.24.0
    - open3d==0.17.0
    - opencv-python==4.9.0.80
    - pandas==2.2.0
    - pillow==10.0.0
    - regex==2023.12.25
    - timm==0.9.16
    - torch==2.1.1
    - tqdm==4.66.2
    - trimesh==4.0.5
    - ultralytics==8.1.14
    - rosnumpy
    - lapx==0.5.5